name = "roll-doradobet-casino"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-doradobet.casino"
HMAC_KEY = "51271bea2528a907f43cef6ec7d03e187115cee8c4cd71564895036c8f013ba4"
COOKIE_NAME = "mse"
PLAY_PATH = "visit-site"
BUTTON_ID = "p912d5665edd5560081c2b5a85328ebe1"
GATE_SALT = "83cae371a844cf9a"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "wq9s"
CTA_SELECTOR = ".play-button"
